jobs:
  build_and_test:
    macos:
      xcode: 16.4
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive --depth 1
      - run:
          name: Build Loop
          command: set -o pipefail && time xcodebuild -workspace LoopWorkspace.xcworkspace -scheme 'LoopWorkspace' -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' build | xcpretty
      - run:
          name: Run Tests
          command: set -o pipefail && time xcodebuild -workspace LoopWorkspace.xcworkspace -scheme 'LoopWorkspace' -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' test | xcpretty
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
